<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Carbon\Carbon;
use App\Models\Admin_Sidebar;

class Admin_SidebarSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Admin_Sidebar::insert([
            [
                'title' => 'Menu',
                'image' => 'fas fa-book-open',
                'link' => 'admin_menu',
                'parent_id' => 0,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Product',
                'image' => 'fas fa-gifts',
                'link' => 'admin_product',
                'parent_id' => 0,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Order',
                'image' => 'fas fa-shopping-basket',
                'link' => 'admin_order',
                'parent_id' => 0,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Category',
                'image' => 'fas fa-edit',
                'link' => 'admin_blog_category',
                'parent_id' => 0,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Blog',
                'image' => 'fas fa-edit',
                'link' => 'admin_blog',
                'parent_id' => 0,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Feedback',
                'image' => 'fas fa-comment',
                'link' => 'admin_feedback',
                'parent_id' => 0,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Gallery',
                'image' => 'fas fa-camera',
                'link' => 'admin_gallery',
                'parent_id' => 0,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Interface',
                'image' => 'fas fa-tools',
                'link' => '',
                'parent_id' => 0,
                'dropdown' => 1,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Icon Mobile',
                'image' => 'fas fa-mobile',
                'link' => 'admin_iconmobile',
                'parent_id' => 0,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Rate star review',
                'image' => 'fas fa-star',
                'link' => 'admin_ratestarview',
                'parent_id' => 0,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Setting',
                'image' => 'fas fa-cogs',
                'link' => '',
                'parent_id' => 0,
                'dropdown' => 1,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Member',
                'image' => 'fas fa-users-cog',
                'link' => '',
                'parent_id' => 0,
                'dropdown' => 1,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Administrator',
                'image' => 'fas fa-user-cog',
                'link' => '',
                'parent_id' => 0,
                'dropdown' => 1,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],

            // Child
            [
                'title' => 'Slide',
                'image' => '',
                'link' => 'admin_slide',
                'parent_id' => 8,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Popup',
                'image' => '',
                'link' => 'admin_popup',
                'parent_id' => 8,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Widget',
                'image' => '',
                'link' => 'admin_widget',
                'parent_id' => 8,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Common Setting',
                'image' => '',
                'link' => 'admin_commonsetting',
                'parent_id' => 11,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Text Setting',
                'image' => '',
                'link' => 'admin_textsetting',
                'parent_id' => 11,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Overview',
                'image' => '',
                'link' => 'admin_overview_member',
                'parent_id' => 12,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Detail',
                'image' => '',
                'link' => 'admin_detail_member',
                'parent_id' => 12,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Overview',
                'image' => '',
                'link' => 'admin_overview_administrator',
                'parent_id' => 13,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'title' => 'Detail',
                'image' => '',
                'link' => 'admin_detail_administrator',
                'parent_id' => 13,
                'dropdown' => 0,
                'display' => 1,
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ]
        ]);
    }
}
